ignore:
  - vulnerability: CVE-2025-46394
    reason: "No fixes to busybox apk available as of 2025-10-16 on Dockerfile base image 22.20.0-alpine3.22"
  - vulnerability: CVE-2024-58251
    reason: "No fixes to busybox apk available as of 2025-10-16 on Dockerfile base image 22.20.0-alpine3.22"
  - vulnerability: CVE-2025-56200
    include-aliases: true
    reason: "No fixes available as of 2025-10-16 on validator npm package"
  - vulnerability: GHSA-5j98-mcp5-4vw2
  - vulnerability: CVE-2025-60876
  - vulnerability: CVE-2025-59465
    reason: "No fixes available as of 2025-10-16 on node 22.20.0"
  - vulnerability: GHSA-34x7-hfp2-rc4v
    reason: "No fixes available as of 2025-10-16 on tar 6.2.1 and 7.4.3"
  - vulnerability: CVE-2025-55131
    reason: "No fixes available as of 2025-10-16 on node 22.20.0"
  - vulnerability: GHSA-r6q2-hw4h-h46w
    reason: "No fixes available as of 2025-10-16 on tar 6.2.1 and 7.4.3"
  - vulnerability: GHSA-8qq5-rm4j-mr97
    reason: "No fixes available as of 2025-10-16 on tar 6.2.1 and 7.4.3"
  - vulnerability: CVE-2025-55130
    reason: "No fixes available as of 2025-10-16 on node 22.20.0"
  - vulnerability: GHSA-xxjr-mmjv-4gpg
    reason: "Medium severity - No fixes available as of 2025-10-16 on lodash 4.17.21 and lodash-es 4.17.21"
  - vulnerability: CVE-2026-21637
    reason: "Medium severity - No fixes available as of 2025-10-16 on node 22.20.0"
  - vulnerability: CVE-2025-59466
    reason: "Medium severity - No fixes available as of 2025-10-16 on node 22.20.0"
  - vulnerability: GHSA-g9mf-h72j-4rw9
    reason: "Medium severity - No fixes available as of 2025-10-16 on undici 6.22.0"
# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
