## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
   "eslint", ## can't upgrade until eslint peer dependency in @typescript-eslint/parser is upgraded
]
