version: 2.1
orbs:
  build: kalinkrustev/build@1.0.10
workflows:
  build_and_test:
    jobs:
      - build/pr_title_check:
          filters:
            branches:
              ignore:
                - main
                - master
      - build/setup:
          filters: &release-condition
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags: &release-tags
              only: /v\d+(\.\d+){2}(-(snapshot|hotfix|perf)\.\d+)?/
      - build/test_dependencies:
          filters:
            branches:
              ignore:
                - main
                - master
          requires:
            - build/setup
      - build/test_lint: &test-condition
          filters: *release-condition
          requires:
            - build/setup
      - build/test_unit: *test-condition
      - build/test_coverage: *test-condition
      - build/vulnerability_check: *test-condition
      - build/audit_licenses: *test-condition
      - build/build_local: *test-condition
      - build/test_integration: &test-docker
          filters: *release-condition
          requires:
            - build/build_local
      - build/test_functional: *test-docker
      - build/license_scan: &scan
          filters: &only-release-tags
            branches:
              ignore:
                - /.*/
            tags: *release-tags
          requires:
            - build/build_local
      - build/image_scan: *scan
      - build/release:
          context: org-global
          filters: &release
            branches:
              only:
                - main
                - master
                - /release\/v.*/
          requires: &tests
            - build/pr_title_check
            - build/test_lint
            - build/test_unit
            - build/test_coverage
            - build/test_integration
            - build/test_functional
            - build/vulnerability_check
            - build/audit_licenses
            - build/license_scan
            - build/image_scan
      - build/github_release:
          context: org-global
          filters: *release
          requires:
            - build/release
      - build/publish_docker: &publish
          context: org-global
          filters: *only-release-tags
          requires: *tests
      - build/publish_npm: *publish
      - build/publish_docker_snapshot: &publish-snapshot
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v\d+(\.\d+){2}(-snapshot\.\d+)?/
          requires: *tests
      - build/publish_npm_snapshot: *publish-snapshot
      - build/publish_npm_prerelease:
          context: org-global
          filters: &only-prerelease-branches
            branches:
              only:
                - /(major|minor|patch)/.*/
          requires:
            - build/test_lint
            - build/test_unit
            - build/test_integration
            - build/test_functional
      - build/publish_docker_prerelease:
          context: org-global
          filters: *only-prerelease-branches
          requires:
            - build/publish_npm_prerelease
