version: 2.1
orbs:
  build: kalinkrustev/build@1.0.10
workflows:
  build_and_test:
    jobs:
      - build/pr_title_check:
          context: org-global
      - build/setup:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
      - build/test_dependencies:
          context: org-global
          filters:
            branches:
              ignore:
                - main
            tags:
              ignore: /.*/
          requires:
            - build/setup
      - build/test_lint:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/setup
      - build/test_unit:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/setup
      - build/test_coverage:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/setup
      - build/test_integration:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/build_local
      - build/test_functional:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/build_local
      - build/vulnerability_check:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/setup
      - build/audit_licenses:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/setup
      - build/build_local:
          context: org-global
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
            tags:
              only: /.*/
          requires:
            - build/setup
      - build/license_scan:
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: >-
                /v[0-9]+(\.[0-9]+)*(\-snapshot(\.[0-9]+)?)?(\-hotfix(\.[0-9]+)?)?(\-perf(\.[0-9]+)?)?/
          requires:
            - build/build_local
      - build/image_scan:
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: >-
                /v[0-9]+(\.[0-9]+)*(\-snapshot(\.[0-9]+)?)?(\-hotfix(\.[0-9]+)?)?(\-perf(\.[0-9]+)?)?/
          requires:
            - build/build_local
      - build/release:
          context: org-global
          filters:
            branches:
              only:
                - main
                - master
                - /release\/v.*/
          requires:
            - build/pr_title_check
            - build/test_lint
            - build/test_unit
            - build/test_coverage
            - build/test_integration
            - build/test_functional
            - build/vulnerability_check
            - build/audit_licenses
            - build/license_scan
            - build/image_scan
      - build/github_release:
          context: org-global
          filters:
            branches:
              only:
                - main
                - /release\/v.*/
          requires:
            - build/release
      - build/publish_docker:
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - build/pr_title_check
            - build/test_lint
            - build/test_unit
            - build/test_coverage
            - build/test_integration
            - build/test_functional
            - build/vulnerability_check
            - build/audit_licenses
            - build/license_scan
            - build/image_scan
      - build/publish_docker_snapshot:
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*\-snapshot+((\.[0-9]+)?)/
          requires:
            - build/pr_title_check
            - build/test_lint
            - build/test_unit
            - build/test_coverage
            - build/test_integration
            - build/test_functional
            - build/vulnerability_check
            - build/audit_licenses
            - build/license_scan
            - build/image_scan
      - build/publish_npm:
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - build/pr_title_check
            - build/test_lint
            - build/test_unit
            - build/test_coverage
            - build/test_integration
            - build/test_functional
            - build/vulnerability_check
            - build/audit_licenses
            - build/license_scan
            - build/image_scan
      - build/publish_npm_snapshot:
          context: org-global
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*\-snapshot+((\.[0-9]+)?)/
          requires:
            - build/pr_title_check
            - build/test_lint
            - build/test_unit
            - build/test_coverage
            - build/test_integration
            - build/test_functional
            - build/vulnerability_check
            - build/audit_licenses
            - build/license_scan
            - build/image_scan
      - build/publish_npm_prerelease:
          context: org-global
          filters:
            branches:
              only:
                - /(major|minor|patch)/.*/
          requires:
            - build/test_lint
            - build/test_unit
            - build/test_integration
            - build/test_functional
      - build/publish_docker_prerelease:
          context: org-global
          filters:
            branches:
              only:
                - /(major|minor|patch)/.*/
          requires:
            - build/publish_npm_prerelease